Repository ES2-UFPI/iparking, pull requests merged in 2022-10, with the labels that each got.

#84 add update user controller # 19
  backend/src/controllers/User/UpdateUserController.ts
Labels: feat

#85 20 add user controller
  backend/src/controllers/Parking/CreateParkingController.ts
  backend/src/controllers/User/CreateUserController.ts
  backend/src/controllers/User/UpdateUserController.ts
  backend/src/routes.ts
Labels: feat

#86 add new paths to swagger.json #68
  backend/src/controllers/Parking/CreateParkingController.ts
  backend/src/controllers/User/CreateUserController.ts
  backend/src/controllers/User/UpdateUserController.ts
  backend/src/controllers/Users/CreateUserController.ts
  backend/src/routes.ts
  backend/src/swagger.json
Labels: documentation

#90 #88 - adicionar testes de validacao de dados de pagamento
  .vscode/settings.json
  iparking_app/lib/ui/pages/pagamento/pagamento_controller.dart
  iparking_app/pubspec.lock
  iparking_app/pubspec.yaml
  iparking_app/test/pagamento_controller_test.dart
Labels: teste

#91 35 acompanhar vagas front
  backend/package-lock.json
  backend/yarn.lock
  iparking_app/lib/data/entities/estacionamento_entity.dart
  iparking_app/lib/data/entities/solicitacoes_entity.dart
  iparking_app/lib/data/entities/usuario_entity.dart
  iparking_app/lib/data/models/estacionamento_model.dart
  iparking_app/lib/data/models/solicitacoes_model.dart
  iparking_app/lib/data/models/usuarios_model.dart
  iparking_app/lib/data/routes/base_url.dart
  iparking_app/lib/data/routes/rotas_estacionamentos.dart
  iparking_app/lib/data/routes/rotas_solicitacoes.dart
  iparking_app/lib/infra/http/http_client.dart
  iparking_app/lib/ui/components/estacionamento_detalhes_bottom_sheet.dart
  iparking_app/lib/ui/pages/estacionamento/cadastro/cadastro_estacionamento.dart
  iparking_app/lib/ui/pages/estacionamento/cadastro/cadastro_estacionamento_controler.dart
  iparking_app/lib/ui/pages/home/components/estacionamento_selecionado.dart
  iparking_app/lib/ui/pages/home/components/menu_page.dart
  iparking_app/lib/ui/pages/home/home_page.dart
  iparking_app/lib/ui/pages/home/map_controller.dart
  iparking_app/lib/ui/pages/login/login_controller.dart
  iparking_app/lib/ui/pages/login/login_page.dart
  iparking_app/lib/ui/pages/reserva/reserva_page.dart
  iparking_app/pubspec.lock
  iparking_app/pubspec.yaml
Labels: feat

#95 20 qrcode front
  backend/src/controllers/Ticket/GetOneTicketController.ts
  iparking_app/lib/data/entities/estacionamento_entity.dart
  iparking_app/lib/data/entities/usuario_entity.dart
  iparking_app/lib/data/models/estacionamento_model.dart
  iparking_app/lib/data/models/solicitacoes_model.dart
  iparking_app/lib/data/models/usuarios_model.dart
  iparking_app/lib/data/routes/base_url.dart
  iparking_app/lib/data/routes/rotas_solicitacoes.dart
  iparking_app/lib/data/routes/rotas_usuario.dart
  iparking_app/lib/infra/http/http_client.dart
  iparking_app/lib/ui/components/estacionamento_detalhes_bottom_sheet.dart
  iparking_app/lib/ui/pages/estacionamento/home/home_estacionamento.dart
  iparking_app/lib/ui/pages/estacionamento/qr_scan/components/bottom_sheet_parking.dart
  iparking_app/lib/ui/pages/estacionamento/qr_scan/components/bottom_sheet_pay_ticket.dart
  iparking_app/lib/ui/pages/estacionamento/qr_scan/components/components.dart
  iparking_app/lib/ui/pages/estacionamento/qr_scan/scan_qrcode_controller.dart
  iparking_app/lib/ui/pages/estacionamento/qr_scan/scan_qrcode_page.dart
  iparking_app/lib/utils/date_format.dart
  iparking_app/lib/utils/price_format.dart
Labels: feat

#97 fix Criação da rota de relatórios
  backend/src/controllers/Ticket/GetAllTicketParkingController.ts
  backend/src/controllers/User/GetOneUserController.ts
  backend/src/routes.ts
Labels: fix

#103 feat: teste para pagina qr_scan
  iparking_app/lib/ui/pages/estacionamento/qr_scan/scan_qrcode_controller.dart
  iparking_app/pubspec.lock
  iparking_app/test/pages/qr_scan_controller_test.dart
Labels: teste
